[build]
  publish = "public"
  command = "yarn build"
  
[build.environment]
  NODE_VERSION = ">=19.6.1"
  
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"

[[plugins]]
  package = "@netlify/plugin-gatsby"
